apiVersion: v1
kind: ServiceAccount
metadata:
  name: aks-ai-agent
  namespace: aks-agent
  labels:
    app.kubernetes.io/name: aks-ai-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: aks-ai-agent-{{ .Chart.Version }}
