apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aks-agent-db
  namespace: aks-agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
